### PR TITLE
Some graphics change.

### PR DESCRIPTION
**Pull request by HeadFox**
Hey ! Now if you can send me the new logo it will be awesome, so i will add it to the website ! 
I think if we can add the nice logo with the effect from the bootanimation in to the website it will bee cool !

### CODE REVIEW

**Comment by westcripp** [comment]
all good but actually previous fonts was better . i didnt like the newest one its too usual .

**Comment by HeadFox** [comment]
Okay no problem ! I will revert it ;) !

**Comment by HeadFox** [comment]
Done ! :)

**Comment by westcripp** [comment]
screenshot_20170218-111509

Actually center layout was better for mobile view . Can you fix it ?

**Comment by HeadFox** [comment]
Yes sure ! I will do it this evening. And the next step Is too replace image/icon with Google Icons.Then i will work on the header. Do you have the RR last logo in HQ ?

**Comment by westcripp** [comment]
Yes but current one is good  for header  I did it for the header . Single logo will look weird . Thanks for improvements btw

**Comment by HeadFox** [comment]
I have some idea in mind now so what I propose is : I will puch mobile fix this evening and then I will create a new branch with a new design proposition (I base my work on the actual design) and you will tell me if you like it or not or if you want to keep/leave some things of want I done.

**Pull request merged**
