### PR TITLE
Style / Design Changes

### PR DESCRIPTION
**Pull request by saif71**
**Following changes has been made this time.**
1. Removed unused icon/font import
2. Added header logo
3. Added prominent download button
4. Added new social icons style
5. Added some cool hover animation
6. Chaged overall page fonts to a more modern font
7. Added favicon

**Proposition**
RR has been my favorite and daily driver for years. Despite being a cutting edge Custom ROM , official web portal of the ROM is out dated (from my opinion).
As a UI / UX designer I feel like I can fix that. So I'm planing to give it a face-lift.  Let me know your opinion. 
Also I want to introduce following sections. 
1. Official Supported device list (could be page containing device list . Like LOS or Paranoid Android) 
2. Official Wiki containing step by step install instruction for supported device list. 
3. May be a page with donor list. it will encourage people to donate to the project. (If you accept donation)
4. Add a FAQ page with common questions and answers. 

Let me know your thoughts. 
Have a nice day !!

### CODE REVIEW

**Comment by sourojitd** [comment]
A great thought! Waiting for devs to take the project forward. Will be happy to help too...

**Comment by saif71** [comment]
Did anyone got a chance to review ? :)

**Comment by westcripp** [comment]
Commit is conflicts

**Comment by westcripp** [comment]
@saif71  Can you update PR?. so i can test new design. Thanks for help

**Review by pnutmath — APPROVED** [review]

**Pull request closed without merging**
